/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Draw;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JColorChooser;

/**
 *
 * @author PHONG VU
 */
public class Drawing extends javax.swing.JFrame {

    Graphics g = null;
    Point p1 = null, p2 = null;
    Color color = Color.RED;

    /**
     * Creates new form Drawing
     */
    public Drawing() {
        initComponents();
        g = this.pnLines.getGraphics();
        btrDrawOnly.setSelected(true);
        btrDrawFill.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TabbledPannel = new javax.swing.JTabbedPane();
        pnLines = new javax.swing.JPanel();
        pnEllipses = new javax.swing.JPanel();
        pnRectangles = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSelect = new javax.swing.JButton();
        btrDrawOnly = new javax.swing.JRadioButton();
        btrDrawFill = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbledPannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbledPannelMouseClicked(evt);
            }
        });

        pnLines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnLinesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnLinesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnLinesLayout = new javax.swing.GroupLayout(pnLines);
        pnLines.setLayout(pnLinesLayout);
        pnLinesLayout.setHorizontalGroup(
            pnLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        pnLinesLayout.setVerticalGroup(
            pnLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        TabbledPannel.addTab("Lines", pnLines);

        pnEllipses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnEllipsesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnEllipsesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnEllipsesLayout = new javax.swing.GroupLayout(pnEllipses);
        pnEllipses.setLayout(pnEllipsesLayout);
        pnEllipsesLayout.setHorizontalGroup(
            pnEllipsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        pnEllipsesLayout.setVerticalGroup(
            pnEllipsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        TabbledPannel.addTab("Ellipses", pnEllipses);

        pnRectangles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnRectanglesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnRectanglesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnRectanglesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnRectanglesLayout = new javax.swing.GroupLayout(pnRectangles);
        pnRectangles.setLayout(pnRectanglesLayout);
        pnRectanglesLayout.setHorizontalGroup(
            pnRectanglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        pnRectanglesLayout.setVerticalGroup(
            pnRectanglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        TabbledPannel.addTab("Rectangles", pnRectangles);

        btnSelect.setText("Select Color");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        buttonGroup1.add(btrDrawOnly);
        btrDrawOnly.setText("Draw Only");

        buttonGroup1.add(btrDrawFill);
        btrDrawFill.setText("Draw and Fill");
        btrDrawFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrDrawFillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btrDrawOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btrDrawFill, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btrDrawOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btrDrawFill, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbledPannel)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabbledPannel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrDrawFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrDrawFillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btrDrawFillActionPerformed

    private void pnRectanglesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRectanglesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnRectanglesMouseClicked

    private void TabbledPannelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbledPannelMouseClicked
        int index = this.TabbledPannel.getSelectedIndex();
        switch (index) {
            case 0:
                g = this.pnLines.getGraphics();
                this.btrDrawFill.setEnabled(false);
                this.btrDrawOnly.setEnabled(true);
                break;
            case 1:
                g = this.pnEllipses.getGraphics();
                this.btrDrawFill.setEnabled(true);
                this.btrDrawOnly.setEnabled(true);
                break;
            case 2:
                g = this.pnRectangles.getGraphics();
                this.btrDrawFill.setEnabled(true);
                this.btrDrawOnly.setEnabled(true);
                break;
        }
        g.setColor(color);
    }//GEN-LAST:event_TabbledPannelMouseClicked

    private void pnLinesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLinesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pnLinesMousePressed

    private void pnLinesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLinesMouseReleased
        p2 = evt.getPoint();
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        p1 = p2 = null;
    }//GEN-LAST:event_pnLinesMouseReleased

    private void pnEllipsesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEllipsesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pnEllipsesMousePressed

    private void pnEllipsesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEllipsesMouseReleased
        p2 = evt.getPoint();
        int left = p1.x < p2.x? p1.x: p2.x;
        int top = p1.y < p2.y? p1.y: p2.y;
        int width = p1.x - p2.x;
        if (width < 0 ) width = -width;
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (btrDrawOnly.isSelected()) {
            g.drawOval(left, top, width, height);
        }else{
            g.fillOval(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_pnEllipsesMouseReleased

    private void pnRectanglesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRectanglesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pnRectanglesMousePressed

    private void pnRectanglesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRectanglesMouseReleased
               p2 = evt.getPoint();
        int left = p1.x < p2.x? p1.x: p2.x;
        int top = p1.y < p2.y? p1.y: p2.y;
        int width = p1.x - p2.x;
        if (width < 0 ) width = -width;
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (btrDrawOnly.isSelected()) {
            g.drawRect(left, top, width, height);
        }else{
            g.fillRect(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_pnRectanglesMouseReleased

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
      color = JColorChooser.showDialog(this, "Choose a color", color.BLACK);
      g.setColor(color);
    }//GEN-LAST:event_btnSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drawing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Drawing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbledPannel;
    private javax.swing.JButton btnSelect;
    private javax.swing.JRadioButton btrDrawFill;
    private javax.swing.JRadioButton btrDrawOnly;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnEllipses;
    private javax.swing.JPanel pnLines;
    private javax.swing.JPanel pnRectangles;
    // End of variables declaration//GEN-END:variables
}
